# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MROIS
email: connect@mindful.community
description: "Portland, Salem, Vancouver WA, Washington, Oregon, Thich Nhat Hanh Events, Retreats, Days of Mindfulness"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mindful.community" # the base hostname & protocol for your site
twitter: peternickol
github:  peternickol
linkedin:  peternickol

# Build settings
markdown: kramdown
